update hook

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -43,5 +43,5 @@ jobs:
             git commit -m "chore: sincronización automática de nuevo episodio"
             git push
             echo "Triggering Vercel Deploy Hook..."
-            curl -sS -X POST "https://api.vercel.com/v1/integrations/deploy/prj_arCETw7mOODxg0Jc1jitYkBinrC6/HPcQgP7hL9" || echo "Warning: Vercel hook trigger failed."
+            curl -sS -X POST "https://api.vercel.com/v1/integrations/deploy/prj_rSg0teeBweEWqlgZc2PDdkJl6lMc/UZeIpBXYVw" || echo "Warning: Vercel hook trigger failed."
           fi
